#
#  Run the IoT data pipeline on a workstation
#
version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=RobotUprising
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.0
    links:
      - elasticsearch      
    ports:
      - "127.0.0.1:5601:5601"
  mqtt:
    image : eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./mosquitto-conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
  logstash:
    container_name: logstash
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
      - ELASTICSEARCH_USER=logstash
      - ELASTICSEARCH_PASSWORD=HereItComes
    volumes:
      - $PWD/logstash-conf/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - $PWD/logstash-conf/conf.d/:/usr/share/logstash/pipeline
    links:
      - elasticsearch
      - mqtt
    restart: always
    build:
      dockerfile: Dockerfile-logstash
      context: .
